from fastapi import APIRouter

from app.api.v1 import (
    addresses,
    attachments,
    backup,
    cables,
    changelog,
    channels,
    color_rules,
    dashboard,
    device_templates,
    devices,
    discovery,
    docs_pages,
    entities,
    imports,
    lists,
    maintenance,
    monitors,
    networks,
    prefixes,
    rack_groups,
    racks,
    ranges,
    reports,
    review,
    scans,
    search,
    settings,
    sites,
    tags,
    topology,
    users,
    vlans,
    vrfs,
)

api_router = APIRouter()
api_router.include_router(settings.router)
api_router.include_router(users.router)
api_router.include_router(maintenance.router)
api_router.include_router(backup.router)
api_router.include_router(sites.router)
api_router.include_router(vrfs.router)
api_router.include_router(prefixes.router)
api_router.include_router(addresses.router)
api_router.include_router(scans.router)
api_router.include_router(dashboard.router)
api_router.include_router(discovery.router)
api_router.include_router(changelog.router)
api_router.include_router(tags.router)
api_router.include_router(vlans.router)
api_router.include_router(ranges.router)
api_router.include_router(networks.router)
api_router.include_router(imports.router)
api_router.include_router(search.router)
api_router.include_router(color_rules.router)
api_router.include_router(entities.circuits_router)
api_router.include_router(entities.certificates_router)
api_router.include_router(entities.assets_router)
api_router.include_router(entities.services_router)
api_router.include_router(lists.router)
api_router.include_router(racks.router)
api_router.include_router(rack_groups.router)
api_router.include_router(devices.router)
api_router.include_router(device_templates.router)
api_router.include_router(cables.router)
api_router.include_router(cables.interfaces_router)
api_router.include_router(monitors.router)
api_router.include_router(channels.router)
api_router.include_router(channels.log_router)
api_router.include_router(review.router)
api_router.include_router(topology.router)
api_router.include_router(reports.router)
api_router.include_router(docs_pages.router)
api_router.include_router(attachments.router)
